server:
  port: 8082
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: dataIn
          binder: kafka1
        output:
          destination: dataOut
          binder: kafka2
      binders:
        kafka1:
         type: kafka
        kafka2:
         type: kafka